name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'adopt'
          java-version: 8.0.432+6
      - name: Cache Maven packages
        uses: actions/cache@v4.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -V javadoc:javadoc -DadditionalJOption=-Xdoclint:none install --file pom.xml
      - name: Publish to personal mave repository
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -V javadoc:javadoc -DadditionalJOption=-Xdoclint:none deploy --file pom.xml
